default:
    path:   / 
    defaults: { _controller: DatabaseBundle:ShowPeople:showAll }

index:
    path:   /index
    defaults: { _controller: DatabaseBundle:ShowPeople:showAll }

new_person:
    path:   /person/new
    defaults: { _controller: DatabaseBundle:AddPerson:new }

show_all:
    path:   /people/showAll
    defaults: { _controller: DatabaseBundle:ShowPeople:showAll }

show_players:
    path:   /people/showPlayers
    defaults: { _controller: DatabaseBundle:ShowPeople:showPlayers }

show_senior:
    path:   /team/showSenior
    defaults: { _controller: DatabaseBundle:ShowTeams:showSenior }

show_female:
    path:   /team/showFemale
    defaults: { _controller: DatabaseBundle:ShowTeams:showFemale }

show_cadete:
    path:   /team/showCadete
    defaults: { _controller: DatabaseBundle:ShowTeams:showCadete }

show_alevin:
    path:   /team/showAlevin
    defaults: { _controller: DatabaseBundle:ShowTeams:showAlevin }

show_benjamin:
    path:   /team/showBenjamin
    defaults: { _controller: DatabaseBundle:ShowTeams:showBenjamin }

show_prebenjamin:
    path:   /team/showPrebenjamin
    defaults: { _controller: DatabaseBundle:ShowTeams:showPrebenjamin }

show_parents:
    path: /people/showParents
    defaults: { _controller: DatabaseBundle:ShowPeople:showParents }

show_members:
    path: /people/showMembers
    defaults: { _controller: DatabaseBundle:ShowPeople:showMembers }

edit_person:
    path:   /person/editPerson/{id}
    defaults: { _controller: DatabaseBundle:EditPerson:editPerson }

delete_person:
    path:   /person/deletePerson/{id}
    defaults: { _controller: DatabaseBundle:AddPerson:deletePerson }

login:
    path:   /login
    defaults: { _controller: DatabaseBundle:Default:login }

admin_menu:
    path:  /admin
    defaults: { _controller: DatabaseBundle:Default:admin }

logout:
    path: /logout
    defaults: { _controller: DatabaseBundle:Default:logout }
