default:
    path:   / 
    defaults: { _controller: DatabaseBundle:People/ShowPeople:showAll }

index:
    path:   /index
    defaults: { _controller: DatabaseBundle:People/ShowPeople:showAll }

new_person:
    path:   /person/new
    defaults: { _controller: DatabaseBundle:People/AddPerson:new }

show_all:
    path:   /people/showAll
    defaults: { _controller: DatabaseBundle:People/ShowPeople:showAll }

show_players:
    path:   /people/showPlayers
    defaults: { _controller: DatabaseBundle:People/ShowPeople:showPlayers }

show_senior:
    path:   /team/showSenior
    defaults: { _controller: DatabaseBundle:People/ShowTeams:showSenior }

show_female:
    path:   /team/showFemale
    defaults: { _controller: DatabaseBundle:People/ShowTeams:showFemale }

show_cadete:
    path:   /team/showCadete
    defaults: { _controller: DatabaseBundle:People/ShowTeams:showCadete }

show_alevin:
    path:   /team/showAlevin
    defaults: { _controller: DatabaseBundle:People/ShowTeams:showAlevin }

show_benjamin:
    path:   /team/showBenjamin
    defaults: { _controller: DatabaseBundle:People/ShowTeams:showBenjamin }

show_prebenjamin:
    path:   /team/showPrebenjamin
    defaults: { _controller: DatabaseBundle:People/ShowTeams:showPrebenjamin }

show_parents:
    path: /people/showParents
    defaults: { _controller: DatabaseBundle:People/ShowPeople:showParents }

show_members:
    path: /people/showMembers
    defaults: { _controller: DatabaseBundle:People/ShowPeople:showMembers }

edit_person:
    path:   /person/editPerson/{id}/{seasonId}
    defaults: { _controller: DatabaseBundle:People/EditPerson:editPerson }

delete_person:
    path:   /person/deletePerson/{id}
    defaults: { _controller: DatabaseBundle:People/AddPerson:deletePerson }

delete_from_team:
    path:   /person/deleteFromTeam/{id}/{season}/{table}
    defaults: { _controller: DatabaseBundle:People/AddPerson:deleteFromTeam }

delete_from_member:
    path:   /person/deleteFromMember/{id}/{season}
    defaults: { _controller: DatabaseBundle:People/AddPerson:deleteFromMember }

login:
    path:   /login
    defaults: { _controller: DatabaseBundle:Default:login }

admin_menu:
    path:  /admin
    defaults: { _controller: DatabaseBundle:Default:admin }

logout:
    path: /logout
    defaults: { _controller: DatabaseBundle:Default:logout }

new_user:
    path:  /admin/newUser
    defaults: { _controller: DatabaseBundle:Admin/Admin:createUser }

show_user:
    path: /admin/showUsers
    defaults: { _controller: DatabaseBundle:Admin/Admin:showUsers }

delete_user:
    path: /admin/deleteUser/{id}
    defaults: { _controller: DatabaseBundle:Admin/Admin:deleteUser }

edit_user:
    path: /admin/editUser/{id}
    defaults: { _controller: DatabaseBundle:Admin/Admin:editUser }

change_password:
    path: /user/changePassword
    defaults: { _controller: DatabaseBundle:User/User:changePassword }

add_season:
    path: /season/newSeason
    defaults: { _controller: DatabaseBundle:User/Season:addSeason }

edit_season:
    path: /season/editSeason/{id}
    defaults: { _controller: DatabaseBundle:User/Season:editSeason }

view_seasons:
    path: /season/showSeasons
    defaults: { _controller: DatabaseBundle:User/Season:showSeasons } 

delete_season:
    path:  /season/deleteSeason/{id}
    defaults: { _controller: DatabaseBundle:User/Season:deleteSeason }
