new_person:
    path:   /person/new
    defaults: { _controller: DatabaseBundle:AddPerson:new }

show_all:
    path:   /person/showAll
    defaults: { _controller: DatabaseBundle:ShowPeople:showAll }

show_players:
    path:   /person/showPlayers
    defaults: { _controller: DatabaseBundle:ShowPeople:showPlayers }

show_person:
    path:   /person/showPerson/{id}
    defaults: { _controller: DatabaseBundle:AddPerson:showPerson }

delete_person:
    path:   /person/deletePerson/{id}
    defaults: { _controller: DatabaseBundle:AddPerson:deletePerson }
