index:
    path:   /index
    defaults: { _controller: DatabaseBundle:ShowPeople:showAll }

new_person:
    path:   /person/new
    defaults: { _controller: DatabaseBundle:AddPerson:new }

show_all:
    path:   /person/showAll
    defaults: { _controller: DatabaseBundle:ShowPeople:showAll }

show_players:
    path:   /person/showPlayers
    defaults: { _controller: DatabaseBundle:ShowPeople:showPlayers }

show_senior:
    path:   /person/showSenior
    defaults: { _controller: DatabaseBundle:ShowTeams:showSenior }

show_female:
    path:   /person/showFemale
    defaults: { _controller: DatabaseBundle:ShowTeams:showFemale }

show_cadete:
    path:   /person/showCadete
    defaults: { _controller: DatabaseBundle:ShowTeams:showCadete }

show_alevin:
    path:   /person/showAlevin
    defaults: { _controller: DatabaseBundle:ShowTeams:showAlevin }

show_benjamin:
    path:   /person/showBenjamin
    defaults: { _controller: DatabaseBundle:ShowTeams:showBenjamin }

show_prebenjamin:
    path:   /person/showPrebenjamin
    defaults: { _controller: DatabaseBundle:ShowTeams:showPrebenjamin }

edit_person:
    path:   /person/editPerson/{id}
    defaults: { _controller: DatabaseBundle:AddPerson:editPerson }

delete_person:
    path:   /person/deletePerson/{id}
    defaults: { _controller: DatabaseBundle:AddPerson:deletePerson }
