# src/DatabaseBundle/Resources/config/validation.yml

DatabaseBundle\Entity\PersonalData:
  properties:
    name: 
      - NotBlank: ~
    surname:
      - NotBlank: ~
    nickname:
    email:
      - Email:
          message: La dirección "{{ value }}" no es válida.
    phone:
    dni: 
    sex:
      - Choice:
          choices: [male, female]
    birthday:

DatabaseBundle\Entity\Pictures:
    properties:
        frontDni:
            - Image:
                minWidth: 400
                maxWidth: 1009
                minHeight: 252
                maxHeight: 638
                mimeTypes: [images/*]
                mimeTypesMessage: "Suba una imagen correcta"
 
        backDni:
            - Image:
                minWidth: 400
                maxWidth: 1009
                minHeight: 252
                maxHeight: 638
