# src/DatabaseBundle/Resources/config/validation.yml

DatabaseBundle\Entity\PersonalData:
  properties:
    name: 
      - NotBlank: ~
    surname:
      - NotBlank: ~
    nickname:
    email:
      - Email:
          message: La dirección "{{ value }}" no es válida.
    phone:
    dni: 
    sex:
      - Choice:
          choices: [male, female]
    birthday:
 
#DatabaseBundle\Entity\FileImport:
#  properties:
#    pathToFile:
#      - File: "application/csv"
