# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        our_db_provider: 
            entity:
                class: DatabaseBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login: 
                login_path: login
                check_path: login
            http_basic: ~
            pattern:   ^/
            provider: our_db_provider

        secured_area:
            anonymous: ~
            logout: 
                path: /logout
                target: /
                invalidate_session: true
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        DatabaseBundle\Entity\User: plaintext
        #Symfony\Component\Security\Core\User\User:
        #    algorithm: bcrypt
        #    cost: 12
