# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    antonio:
                        password: $2y$12$/Y9jkEE9hdCQOS2s/Q8Gt.UlLcTNkOYsubXWVx/GjRr8pp76dkIy.
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$rlyCfeh5eUYy4Jcg8i2VAulgdJDEZDFzYJB1cseyTwuQrypQw9Tuu
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login: 
                login_path: login
                check_path: login

            http_basic: ~
            pattern:   ^/

        secured_area:
            anonymous: ~
            logout: 
                path: /logout
                target: /
                invalidate_session: true
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
