DatabaseBundle\Entity\CoachData:
    type: entity
    table: coachData
    repositoryClass: DatabaseBundle\Repository\CoachDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        salary:
            type: float
            nullable: true
        category:
            type: string
            length: '20'
            nullable: true
        number:
            type: integer
            nullable: true

    lifecycleCallbacks: {  }

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: coachData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]

        personalData:
            targetEntity: PersonalData
            inversedBy: coachData
            joinColumn:
                name: personalData_id
                referencedColumnName: id

    oneToOne:
        coachPerson:
            targetEntity: CoachPerson
            mappedBy: coachData
            cascade: ["persist", "remove"]

        dateData:
            targetEntity: DateData
            inversedBy: dateData
            joinColumn:
                name: date_id
                referencedColumnName: id
            cascade: ["persist", "remove"]
