DatabaseBundle\Entity\CoachData:
    type: entity
    table: coachData
    repositoryClass: DatabaseBundle\Repository\CoachDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        salary:
            type: float
            nullable: true
        category:
            type: string
            length: '20'
            nullable: true
        season:
            type: integer
    lifecycleCallbacks: {  }

    manyToOne:
    #oneToOne:
        personalData:
            targetEntity: PersonalData
            #mappedBy: coachData
            inversedBy: coachData
            joinColumn:
                name: personalData_id
                referencedColumnName: id
                nullable: true
                onDelete: 'CASCADE'
            cascade: ["persist"]

