DatabaseBundle\Entity\CoachData:
    type: entity
    table: coachData
    repositoryClass: DatabaseBundle\Repository\CoachDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        salary:
            type: float
            nullable: true
        category:
            type: string
            length: '20'
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: coachData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]

        wholePerson:
            targetEntity: WholePerson
            inversedBy: coachData
            joinColumn:
                name: wholePerson_id
                referencedColumnName: id
