DatabaseBundle\Entity\CoachData:
    type: entity
    table: coachData
    repositoryClass: DatabaseBundle\Repository\CoachDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        salary:
            type: float
            nullable: true
        category:
            type: string
            length: '20'
            nullable: true
        season:
            type: integer
    lifecycleCallbacks: {  }

    oneToOne:
        wholePerson:
            targetEntity: WholePerson
            mappedBy: coachData
            cascade: ["persist", "remove"]
