# src/DatabaseBundle/Resources/config/doctrine/FileImport.orm.yml
DatabaseBundle\Entity\FileImport:
  type: entity
  table: fileImport
  repositoryClass: DatabaseBundle\Repository\FileImportRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    importedDate:
      type: datetime
      nullable: true

    pathToFile:
      type: string
      nullable: false

    content:
      type: string
      nullable: false
