DatabaseBundle\Entity\MemberData:
    type: entity
    table: memberData
    repositoryClass: DatabaseBundle\Repository\MemberDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        season:
            type: integer
        payment:
            type: float
            nullable: true
        memberId:
            type: integer
    lifecycleCallbacks: {  }

    manyToOne:
        wholePerson:
            targetEntity: WholePerson
            inversedBy: memberData
            joinColumn:
                name: wholePerson_id
                referencedColumnName: id
                nullable: false
                onDelete: 'CASCADE'
            cascade: ["persist"]
