DatabaseBundle\Entity\MemberData:
    type: entity
    table: memberData
    repositoryClass: DatabaseBundle\Repository\MemberDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        payment:
            type: float
            nullable: true
        memberId:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: memberData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]

        personalData:
            targetEntity: PersonalData
            inversedBy: memberData
            joinColumn:
                name: personalData_id
                referencedColumnName: id
