DatabaseBundle\Entity\MemberData:
    type: entity
    table: memberData
    repositoryClass: DatabaseBundle\Repository\MemberDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        payment:
            type: float
            nullable: true
        memberId:
            type: integer
    lifecycleCallbacks: {  }

    oneToOne:
        wholePerson:
            targetEntity: WholePerson
            mappedBy: memberData

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: memberData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]
