DatabaseBundle\Entity\MemberData:
    type: entity
    table: memberData
    repositoryClass: DatabaseBundle\Repository\MemberDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        payment:
            type: float
            nullable: true
        memberId:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: memberData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]

    oneToOne:
        memberPerson:
            targetEntity: MemberPerson
            mappedBy: memberData
            cascade: ["persist", "remove"]

        pay:
            targetEntity: Pay
            inversedBy: memberData
            joinColumn:
                name: pay_id
                referencedColumnName: id
            cascade: ["persist", "remove"]

        dateData:
            targetEntity: DateData
            inversedBy: memberData
            joinColumn:
                name: date_id
                referencedColumnName: id
            cascade: ["persist", "remove"]
