DatabaseBundle\Entity\ParentData:
    type: entity
    table: parentData
    repositoryClass: DatabaseBundle\Repository\ParentDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        season:
            type: integer
    lifecycleCallbacks: {  }

    oneToOne:
        wholePerson:
            targetEntity: WholePerson
            mappedBy: parentData

    manyToMany:
        playerData:
            targetEntity: PlayerData
            inversedBy: parentData
            joinTable:
                name: parentData_playerData
                joinColumns:
                  parent_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  player_id:
                    referencedColumnName: id
                onDelete: 'CASCADE'
            cascade: ["persist"]
                  
