DatabaseBundle\Entity\ParentData:
    type: entity
    table: parentData
    repositoryClass: DatabaseBundle\Repository\ParentDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        season:
            type: integer
    lifecycleCallbacks: {  }

    manyToOne:
    #oneToOne:
        personalData:
            targetEntity: PersonalData
            #mappedBy: playerData
            inversedBy: parentData
            joinColumn:
                name: personalData_id
                referencedColumnName: id
                nullable: true
                onDelete: 'CASCADE'
            cascade: ["persist"]
