DatabaseBundle\Entity\ParentData:
    type: entity
    table: parentData
    repositoryClass: DatabaseBundle\Repository\ParentDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    lifecycleCallbacks: {  }

    manyToMany:
        playerData:
            targetEntity: PlayerData
            inversedBy: parentData
            joinTable:
                name: parentData_playerData
                joinColumns:
                  parent_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  player_id:
                    referencedColumnName: id
                onDelete: 'CASCADE'
            cascade: ["persist", "remove"]
                  
    manyToOne:
        season:
            targetEntity: Season
            inversedBy: parentData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]

        personalData:
            targetEntity: PersonalData
            inversedBy: parentData
            joinColumn:
                name: personalData_id
                referencedColumnName: id

    oneToOne:
        parentPerson:
            targetEntity: ParentPerson
            mappedBy: parentData
            cascade: ["persist", "remove"]
