# src/DatabaseBundle/Resources/config/doctrine/Pay.orm.yml
DatabaseBundle\Entity\Pay:
  type: entity
  table: pay
  repositoryClass: DatabaseBundle\Repository\PayRepository
  id:
    id:
        type: integer
        generator:  { strategy: AUTO }

  fields:
    wayOfPayment:
      type: string
      nullable: false
      length: 20
    person:
      type: string
      nullable: true
    accountNumber:
      type: bigint
      nullable: true
    totalAmount:
      type: integer
      nullable: true
      lenght: 150

  oneToOne:
    playerData:
      targetEntity: PlayerData
      inversedBy: pay
      joinColumn:
          name: playerData_id
          referencedColumnName: id
      cascade: ["persist", "remove"]

  oneToMany:
     payment:
        targetEntity: Payment 
        mappedBy: pay
        cascade: ["persist", "remove"]
