# src/DatabaseBundle/Resources/config/doctrine/Payment.orm.yml
DatabaseBundle\Entity\Payment:
  type: entity
  table: payment
  repositoryClass: DatabaseBundle\Repository\PaymentRepository
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: AUTO

  fields:
      paymentDate:
          type: datetime
          nullable: false
      amountPayed:
          type: integer
          nullable: false
      status:
          type: string
          nullable: true
      active:
          type: boolean
          nullable: true

  manyToOne:
      pay:
          targetEntity: Pay 
          inversedBy: payment
          joinColumn:
              name: pay_id
              referencedColumnName: id

      paymentHistory:
          targetEntity: PaymentHistory
          inversedBy: payment
          joinColumn:
              name: paymentHistory_id
              referencedColumnName: id
          cascade: ["persist", "remove"]
          


