# src/DatabaseBundle/Resources/config/doctrine/Payment.orm.yml
DatabaseBundle\Entity\Payment:
  type: entity
  table: payment
  repositoryClass: DatabaseBundle\Repository\PaymentRepository
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: AUTO

  fields:
      person:
          type: string
          lenght: 150
      accountNumber:
          type: bigint
          nullable: true
      paymentDate:
          type: datetime
          nullable: false
      amountPayed:
          type: integer
          nullable: false
      status:
          type: string
          nullable: true

  manyToOne:
      pay:
          targetEntity: Pay 
          inversedBy: pay
          joinColumn:
              name: pay_id
              referencedColumnName: id
