# src/DatabaseBundle/Resources/config/doctrine/PersonalData.orm.yml
DatabaseBundle\Entity\PersonalData:
  type: entity
  table:  personalData
  repositoryClass: DatabaseBundle\Repository\PersonalDataRepository
  id:
    id:
        type: integer
        generator:  { strategy: AUTO }

  fields:
    name:
        type: string
        length: 40
        nullable: false

    surname:
        type: string
        length: 150
        nullable: false

    nickname:
        type: string
        length: 30
        nullable: true

    email:
        type: string
        lengtlh: 255
        nullable: true

    phone:
        type: bigint
        nullable: true

    dni:
        type: string
        length: 10
        nullable: true
        unique: true
 
    birthday:
        type: datetime
        nullable: true

    sex:
        type: string

    isPlayer:
        type: boolean
        default: false

    isCoach:
        type: boolean
        default: false

    isMember:
        type: boolean
        default: false

    isParent:
        type: boolean
        default: false

  oneToOne:
      wholePerson:
        targetEntity: WholePerson
        mappedBy: personalData
