# src/DatabaseBundle/Resources/config/doctrine/PersonalData.orm.yml
DatabaseBundle\Entity\PersonalData:
  type: entity
  table:  personalData
  repositoryClass: DatabaseBundle\Repository\PersonalDataRepository
  id:
    id:
        type: integer
        generator:  { strategy: AUTO }

  fields:
    name:
        type: string
        length: 40
        nullable: false

    surname:
        type: string
        length: 150
        nullable: false

    nickname:
        type: string
        length: 30
        nullable: true

    dni:
        type: string
        length: 10
        nullable: true
        unique: true
 
    birthday:
        type: datetime
        nullable: true

    sex:
        type: string

    isParent:
        type: boolean
        default: false

  oneToOne:
    authorization:
      targetEntity: Authorization
      mappedBy: personalData
      cascade: ["persist"]

    contactData:
      targetEntity: ContactData
      mappedBy: personalData
      cascade: ["persist", "remove"]

  oneToMany:
    playerData:
      targetEntity: PlayerData
      mappedBy: personalData
      cascade: ["persist", "remove"]

    coachData:
      targetEntity: CoachData
      mappedBy: personalData
      cascade: ["persist", "remove"]

    memberData:
      targetEntity: MemberData
      mappedBy: personalData
      cascade: ["persist", "remove"]

    parentData:
      targetEntity: ParentData
      mappedBy: personalData
      cascade: ["persist", "remove"]

    playerPerson:
        targetEntity: PlayerPerson
        mappedBy: personalData
        cascade: ["persist", "remove"]

    coachPerson:
        targetEntity: CoachPerson
        mappedBy: personalData
        cascade: ["persist", "remove"]

    memberPerson:
        targetEntity: MemberPerson
        mappedBy: personalData
        cascade: ["persist", "remove"] 
