# src/DatabaseBundle/Resources/config/doctrine/PersonNumber.orm.yml
DatabaseBundle\Entity\PersonNumber:
    type: entity
    table: personNumber
    repositoryClass: DatabaseBundle\Repository\PersonNumberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        number:
            type: integer
            nullable: true

    lifecycleCallbacks: {  }

    oneToMany:
        playerData:
            targetEntity: PlayerData
            mappedBy: personNumber
            cascade: ["remove"]
