# src/DatabaseBundle/Resources/config/doctrine/Pictures.orm.yml
DatabaseBundle\Entity\Pictures:
    type: entity
    table: pictures
    repositoryClass: DatabaseBundle\Repository\PicturesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        frontDni:
            type: string
            length: 350
            nullable: true

        backDni:
            type: string
            length: 350
            nullable: true
        
        healthCareCard:
            type: string
            length: 350
            nullable: true
        
        familyBook:
            type: string
            length: 350
            nullable: true

    oneToOne:
        personalData:
            targetEntity: PersonalData
            inversedBy: pictures
            joinColumn:
                name: personalData_id
                referencedColumnName: id
            
