# src/DatabaseBundle/Resources/config/doctrine/PlayerData.orm.yml
DatabaseBundle\Entity\PlayerData:
    type: entity
    table: playerData
    repositoryClass: DatabaseBundle\Repository\PlayerDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        payment:
            type: float
            nullable: true
        category:
            type: string
            length: '150'
            
    lifecycleCallbacks: {  }

    manyToMany:
        parentData:
            targetEntity: ParentData
            mappedBy: playerData
            cascade: ["persist", "remove"]

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: playerData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]

        wholePerson:
            targetEntity: WholePerson
            inversedBy: playerData
            joinColumn:
                name: wholePerson_id
                referencedColumnName: id
