# src/DatabaseBundle/Resources/config/doctrine/PlayerData.orm.yml
DatabaseBundle\Entity\PlayerData:
    type: entity
    table: playerData
    repositoryClass: DatabaseBundle\Repository\PlayerDataRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category:
            type: string
            length: 150
        number:
            type: integer
            nullable: true
            
    lifecycleCallbacks: {  }

    manyToMany:
        parentData:
            targetEntity: ParentData
            mappedBy: playerData
            cascade: ["persist", "remove"]

    manyToOne:
        season:
            targetEntity: Season
            inversedBy: playerData
            joinColumn: 
                name: season_id
                referencedColumnName: id
            cascade: ["persist"]

        personalData:
            targetEntity: PersonalData
            inversedBy: playerData
            joinColumn:
                name: personalData_id
                referencedColumnName: id

    oneToOne:
        pay:
            targetEntity: Pay
            inversedBy: playerData
            joinColumn:
                name: pay_id
                referencedColumnName: id
            cascade: ["persist", "remove"]
            
        playerPerson:
            targetEntity: PlayerPerson
            mappedBy: playerData
            cascade: ["persist", "remove"]

        dateData:
            targetEntity: DateData
            inversedBy: dateData
            joinColumn:
                name: date_id
                referencedColumnName: id
            cascade: ["persist", "remove"]
