DatabaseBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: DatabaseBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        username:
            type: string
            length: 35
            nullable: false
        password:
            type: string
            length: 4096
            nullable: false 
        roles:
            type: string
            length: 12
            nullable: true 

    lifecycleCallbacks: {  }
