# src/DatabaseBundle/Resources/config/doctrine/WholePerson.orm.yml
DatabaseBundle\Entity\WholePerson:
  type: entity
  table: wholePerson
  repositoryClass: DatabaseBundle\Repository\WholePersonRepository
  id:
    id:
      type: integer
      generator:  { strategy: AUTO }

  oneToOne:
    personalData:
      targetEntity: PersonalData
      inversedBy: wholePerson
      joinColumn: 
        name: personalData_id
        referencedColumnName: id
        onDelete: 'CASCADE'
      cascade: ["persist"]

    playerData:
      targetEntity: PlayerData
      inversedBy: wholePerson
      joinColumn: 
        name: playerData_id
        referencedColumnName: id
        onDelete: 'CASCADE'
      cascade: ["persist"]

    coachData:
      targetEntity: CoachData
      inversedBy: wholePerson
      joinColumn:
        name: coachData_id
        referencedColumnName: id
        onDelete: 'CASCADE'
      cascade: ["persist"]

    memberData:
      targetEntity: MemberData
      inversedBy: wholePerson
      joinColumn:
        name: memberData_id
        referencedColumnName: id
        onDelete: 'CASCADE'
      cascade: ["persist"]

    parentData:
      targetEntity: ParentData
      inversedBy: wholePerson
      joinColumn:
        name: parentData_id
        referencedColumnName: id
        onDelete: 'CASCADE'
      cascade: ["persist"]
