<?php

namespace DatabaseBundle\Repository;

/**
 * ActivePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivePaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
