<?php

namespace DatabaseBundle\Repository;

/**
 * AuthorizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizationRepository extends \Doctrine\ORM\EntityRepository
{
}
