<?php

namespace DatabaseBundle\Repository;

/**
 * CoachPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
