<?php

namespace DatabaseBundle\Repository;

/**
 * CoachPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachPersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCoachPerson($id, $season)
    {
        $query = $this->createQueryBuilder('coachPerson')
                ->join('coachPerson.personalData', 'personalData')
                ->join('coachPerson.coachData', 'coachData')
                ->join('coachData.season', 'season')
                ->where('personalData.id = :id')
                ->andWhere('season.id = :season')
                ->setParameter('id', $id)
                ->setParameter('season', $season)
                ->getQuery();
        return $query->getOneOrNullResult();
                
    }
}
