<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoachDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachDataRepository extends EntityRepository
{
    public function getCategory($id, $season)
    {
       $query = $this->createQueryBuilder('coaches')
                ->join('coaches.coachPerson', 'coachperson')
                ->join('coachperson.personalData', 'personaldata')
                ->join('coaches.season', 'season')
                ->where('person.id = :id')
                ->andWhere('season.id = :seasonId')
                ->setParameter('id', $id)
                ->setParameter('seasonId', $season)
                ->getQuery();
        return $query->getOneOrNullResult();
    }

    public function getByCategory($name, $seasonId, $page)
    {
        $query = $this->createQueryBuilder('coaches')
            ->join('coaches.coachPerson', 'coachperson')
            ->join('coachperson.personalData', 'personaldata')
            ->join('coaches.season', 'season')
            ->where('coaches.category LIKE :category')
            ->andWhere('season.id = :seasonId')
            ->setParameter('category', $name)
            ->setParameter('seasonId', $seasonId)
            ->orderBy('personaldata.surname')
            ->getQuery();
        $paginator = \DatabaseBundle\Repository\PaginatorRepository::paginate($query, $page);
        return array('paginator' => $paginator,
                    'query' => $query);
    }
}
?>
}
