<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoachDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachDataRepository extends EntityRepository
{
    private function getCategory($id, $season)
    {
       $query = $this->createQueryBuilder('coaches')
                ->join('coaches.personalData', 'person')
                ->join('coaches.season', 'season')
                ->where('person.id = :id')
                ->andWhere('season.id = :seasonId')
                ->setParameter('id', $id)
                ->setParameter('seasonId', $season)
                ->getQuery();
        return $query->getOneOrNullResult();
    }
}
