<?php

namespace DatabaseBundle\Repository;

/**
 * ContactDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getContactData($personId)
    {
        $query = $this->createQueryBuilder('contact')
            ->from('DatabaseBundle:ContactData', 'data')
            ->join('contact.personalData', 'person')
            ->where('person.id = :id')
            ->setParameter('id', $personId)
            ->getQuery();
        return $query->getOneOrNullResult();
    }
}
