<?php

namespace DatabaseBundle\Repository;

/**
 * DateDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateDataRepository extends \Doctrine\ORM\EntityRepository
{
}
