<?php

namespace DatabaseBundle\Repository;

/**
 * FileImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileImportRepository extends \Doctrine\ORM\EntityRepository
{
}
