<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberDataRepository extends EntityRepository
{
}
