<?php

namespace DatabaseBundle\Repository;

/**
 * MemberPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
