<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberDataRepository extends EntityRepository
{
    public function deleteFromMember($id, $seasonId) {
        $query = $this->createQueryBuilder('members')
            ->join('members.memberPerson', 'memberperson')
            ->join('memberperson.personalData', 'personaldata')
            ->join('members.season', 'season')
            ->where('personaldata.id = :id')
            ->andWhere('season.id = :seasonId')
            ->setParameter('id', $id)
            ->setParameter('seasonId', $seasonId)
            ->getQuery();
        return $query->getOneOrNullResult();
    }
}
