<?php

namespace DatabaseBundle\Repository;

/**
 * ParentPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
