<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParentDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentDataRepository extends EntityRepository
{
    public function deleteFromParent($id, $seasonId) {
        $query = $this->createQueryBuilder('parents')
            ->join('parents.parentPerson', 'parentperson')
            ->join('parentperson.personalData', 'personaldata')
            ->join('parents.season', 'season')
            ->where('personaldata.id = :id')
            ->andWhere('season.id = :seasonId')
            ->setParameter('id', $id)
            ->setParameter('seasonId', $seasonId)
            ->getQuery();
        return $query->getOneOrNullResult();
    }
}
