<?php

namespace DatabaseBundle\Repository;

/**
 * PaymentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
