<?php

namespace DatabaseBundle\Repository;

/**
 * PayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPay($id)
    {
        $query = $this->createQueryBuilder('pay')
                ->join('pay.playerData', 'playerData')
                ->where('playerData.id = :id')
                ->setParameter('id', $id)
                ->getQuery();
        return $query->getResult();
    }
}
