<?php

namespace DatabaseBundle\Repository;

/**
 * PayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayRepository extends \Doctrine\ORM\EntityRepository
{
}
