<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PersonalDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalDataRepository extends EntityRepository
{
    public function savePerson($personalData, $edit)
    {
        $em = $this->getEntityManager();
        if ($edit)
            $em->merge($personalData);
        $em->persist($personalData);
        $em->flush();
    }

    public function paginate($dql, $page = 1, $limit = 20)
    {
        $paginator = new Paginator($dql);
        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit
    
        return $paginator;
    }

    public function getAll($currentPage = 1, $limit = 20)
    {
        $em = $this->getEntityManager();
        $personalData = $this->createQueryBuilder('c')
                ->orderBy('c.surname', 'ASC');
        $paginator = $this->paginate($personalData, $currentPage, $limit);
        return array('paginator' => $paginator, 
                    'personalData' => $personalData);
    }
}
