<?php

namespace DatabaseBundle\Repository;

/**
 * PersonNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
