<?php

namespace DatabaseBundle\Repository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicturesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPictures($id)
    {
       $query = $this->createQueryBuilder('pictures')
                ->join('pictures.personalData', 'personalData')
                ->where('personalData.id = :id')
                ->setParameter('id', $id)
                ->getQuery();
        return $query->getOneOrNullResult(); 
    }
}
