<?php

namespace DatabaseBundle\Repository;

/**
 * PlayerPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
