<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerDataRepository extends EntityRepository
{
    public function getCategory($id, $season)
    {
       $query = $this->createQueryBuilder('players')
                ->join('players.playerPerson', 'players')
                ->join('playerperson.personalData', 'personaldata')
                ->join('players.personalData', 'person')
                ->join('players.season', 'season')
                ->where('person.id = :id')
                ->andWhere('season.id = :seasonId')
                ->setParameter('id', $id)
                ->setParameter('seasonId', $season)
                ->getQuery();
        return $query->getOneOrNullResult();
    }


    public function getByCategory($name, $seasonId, $page)
    {
        $query = $this->createQueryBuilder('players')
            ->join('players.playerPerson', 'playerperson')
            ->join('playerperson.personalData', 'personaldata')
            ->join('players.season', 'season')
            ->where('players.category LIKE :category')
            ->andWhere('season.id = :seasonId')
            ->setParameter('category', $name)
            ->setParameter('seasonId', $seasonId)
            ->orderBy('personaldata.surname')
            ->getQuery();
        $paginator = \DatabaseBundle\Repository\PaginatorRepository::paginate($query, $page);
        return array('paginator' => $paginator,
                    'query' => $query);
    }
}
?>
