<?php

namespace DatabaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    public function getIdFromText($seasontext)
    {
        return $this->createQueryBuilder('s')
            ->where('s.seasontext = :seasontext')
            ->setParameter('seasontext', $seasontext)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAll()
    {
        return $this->findBy(array(), array('startingyear' => 'ASC'));
    }

    public function getDefaultSeason()
    {
        return $this->createQueryBuilder('s')
            ->where('s.defaultseason = :true')
            ->setParameter('true', 1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function countSeasons()
    {
        return $this->createQueryBuilder('s')
            ->select('count(s.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function setAsNotDefault($season)
    {
        $season->setDefaultseason(false);  
    }
}
