<?php

namespace DatabaseBundle\Repository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends \Doctrine\ORM\EntityRepository
{
  public function getIdFromText($seasontext)
  {
    return $this->createQueryBuilder('s')
        ->where('s.seasontext = :seasontext')
        ->setParameter('seasontext', $seasontext)
        ->getQuery()
        ->getOneOrNullResult();
  }

  public function findAll()
  {
    return $this->findBy(array(), array('startingyear' => 'ASC'));
  }
}
