<?php

namespace DatabaseBundle\Repository;

/**
 * WholePersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WholePersonRepository extends \Doctrine\ORM\EntityRepository
{
}
